"""initial_schema

Revision ID: 4e47b85cd03f
Revises: 
Create Date: 2026-09-30 19:38:08.754750
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4e47b85cd03f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calc_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formula_id', sa.String(length=100), nullable=False),
    sa.Column('formula_version', sa.Integer(), nullable=False),
    sa.Column('input_ids', sa.JSON(), nullable=False),
    sa.Column('output_value', sa.String(length=100), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calc_run_input_hash'), 'calc_run', ['input_hash'], unique=False)
    op.create_table('org_unit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_type', sa.Enum('ORGANISATION', 'SUBSIDIARY', 'AREA', 'MINE', 'DIVISION', name='org_unit_type'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource', 'action')
    )
    op.create_table('report_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('period', sa.Enum('SHIFT', 'DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'ANNUAL', name='report_period'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mine',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_unit_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('shift_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('report_template_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['report_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keycloak_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keycloak_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('approval_chain',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bench',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bench_level', sa.String(length=50), nullable=False),
    sa.Column('geom', sa.JSON(), nullable=True, comment='GeoJSON polygon, srid=4326'),
    sa.Column('elevation_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_forecast',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('precipitation_mm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('temperature_max', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_observation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('observation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_max', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('temperature_min', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('precipitation_mm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('wind_speed_kmh', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mine_id', 'observation_date', 'source')
    )
    op.create_table('approval_level',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chain_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('rule', sa.Enum('ANY_OF', 'ALL_OF', name='approval_rule_type'), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('escalation_role', sa.String(length=100), nullable=True),
    sa.Column('can_skip', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['approval_chain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('chain_id', sa.UUID(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'RETURN', 'ESCALATE', 'WITHDRAW', name='approval_action_type'), nullable=True),
    sa.Column('acted_by', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=255), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acted_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['chain_id'], ['approval_chain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'RETURN', 'ESCALATE', 'SUBMIT', 'SYNC', 'LOGIN', 'RESOLVE_CONFLICT', 'GENERATE_REPORT', 'VERIFY_CHAIN', 'ACCEPT_PLAN', 'REJECT_PLAN', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created', 'audit_event', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_event', ['entity_type', 'entity_id'], unique=False)
    op.create_table('chat_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conflict_flag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value_a', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_a', sa.String(length=255), nullable=False),
    sa.Column('value_b', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_b', sa.String(length=255), nullable=False),
    sa.Column('tolerance_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('resolution', sa.Enum('UNRESOLVED', 'ACCEPT_PRIMARY', 'ACCEPT_SECONDARY', 'CORRECTED', name='conflict_resolution'), nullable=False),
    sa.Column('resolved_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('doc_type', sa.Enum('PDF', 'IMAGE', 'EXCEL', 'CSV', 'WORD', 'POWERPOINT', 'OTHER', name='document_type'), nullable=False),
    sa.Column('category', sa.Enum('GEOLOGICAL', 'PRODUCTION', 'EQUIPMENT', 'SAFETY', 'ENVIRONMENTAL', 'PLANNING', 'FINANCIAL', 'HISTORICAL', 'OTHER', name='document_category'), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('ingestion_status', sa.Enum('UPLOADED', 'PROCESSING', 'OCR_COMPLETE', 'STRUCTURED', 'EMBEDDED', 'INDEXED', 'REVIEW_PENDING', 'REVIEWED', 'FAILED', name='ingestion_status'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gap_tonnes', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('proposed_daily_targets', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('historical_evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACCEPTED', 'REJECTED', 'MODIFIED', name='recovery_plan_status'), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Enum('SHIFT', 'DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'ANNUAL', name='report_report_period'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'RETURNED', 'FINALIZED', name='report_status'), nullable=False),
    sa.Column('generated_description', sa.Text(), nullable=False),
    sa.Column('edited_description', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('calc_run_id', sa.UUID(), nullable=True),
    sa.Column('export_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['calc_run_id'], ['calc_run.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_batch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entries_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('target',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('bench_id', sa.UUID(), nullable=True),
    sa.Column('period', sa.Enum('ANNUAL', 'HALF_YEARLY', 'QUARTERLY', 'MONTHLY', 'WEEKLY', 'DAILY', 'SHIFT', name='target_period'), nullable=False),
    sa.Column('metric', sa.Enum('PRODUCTION_TONNES', 'OVERBURDEN_M3', 'STRIPPING_RATIO', 'OB_COAL_RATIO', 'OPERATING_HOURS', 'DOWNTIME_HOURS', 'EQUIPMENT_AVAILABILITY', 'DISPATCH_TONNES', 'WORKERS_PRESENT', name='target_metric_name'), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parent_target_id', sa.UUID(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bench_id'], ['bench.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.ForeignKeyConstraint(['parent_target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_term',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('route_type', sa.Enum('NUMERIC', 'CONTEXTUAL', 'HYBRID', 'PLANNING', 'OUT_OF_SCOPE', name='query_route_type'), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True, comment='1024-dim float[] for BGE-M3'),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_chunk_tsv', 'doc_chunk', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('document_page',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('ocr_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('image_key', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('table_data', sa.JSON(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_value_staging',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_bbox', sa.JSON(), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'ACCEPTED', 'EDITED', 'REJECTED', name='staging_review_status'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_value',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('row_key', sa.String(length=200), nullable=False),
    sa.Column('calc_run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['calc_run_id'], ['calc_run.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('bench_id', sa.UUID(), nullable=True),
    sa.Column('shift_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shift_number', sa.Enum('FIRST', 'SECOND', 'THIRD', name='shift_number'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'SYNCED', 'UNDER_REVIEW', 'RETURNED', 'APPROVED', 'REJECTED', name='entry_status'), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('previous_version_id', sa.UUID(), nullable=True),
    sa.Column('sync_batch_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bench_id'], ['bench.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['shift_entry.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['sync_batch_id'], ['sync_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shift_entry_mine_date', 'shift_entry', ['mine_id', 'shift_date', 'shift_number'], unique=False)
    op.create_table('entry_attachment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shift_entry_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shift_entry_id'], ['shift_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry_value',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shift_entry_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.Enum('PRODUCTION_TONNES', 'OVERBURDEN_M3', 'STRIPPING_RATIO', 'OB_COAL_RATIO', 'OPERATING_HOURS', 'DOWNTIME_HOURS', 'EQUIPMENT_AVAILABILITY', 'DISPATCH_TONNES', 'WORKERS_PRESENT', name='metric_name'), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shift_entry_id'], ['shift_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineage_edge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_value_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['report_value_id'], ['report_value.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lineage_source', 'lineage_edge', ['source_type', 'source_id'], unique=False)
    op.create_table('cause_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shift_entry_id', sa.UUID(), nullable=False),
    sa.Column('cause_type', sa.Enum('RAIN_WEATHER', 'EQUIPMENT_FAILURE', 'FIRE_MAJOR_INCIDENT', 'LABOUR_DISRUPTION', 'SUPPLY', 'POWER_FAILURE', 'BLASTING_DELAY', 'OTHER', name='cause_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hours_lost', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('evidence_attachment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_attachment_id'], ['entry_attachment.id'], ),
    sa.ForeignKeyConstraint(['shift_entry_id'], ['shift_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_flag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('bench_id', sa.UUID(), nullable=True),
    sa.Column('flag_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('actual_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('anomaly_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('contributing_features', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('FLAGGED', 'ACKNOWLEDGED', 'DISMISSED', 'LINKED_TO_CAUSE', name='anomaly_status'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=False),
    sa.Column('linked_cause_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bench_id'], ['bench.id'], ),
    sa.ForeignKeyConstraint(['linked_cause_id'], ['cause_record.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomaly_flag')
    op.drop_table('cause_record')
    op.drop_index('ix_lineage_source', table_name='lineage_edge')
    op.drop_table('lineage_edge')
    op.drop_table('entry_value')
    op.drop_table('entry_attachment')
    op.drop_index('ix_shift_entry_mine_date', table_name='shift_entry')
    op.drop_table('shift_entry')
    op.drop_table('report_value')
    op.drop_table('extracted_value_staging')
    op.drop_table('extracted_table')
    op.drop_table('document_page')
    op.drop_index('ix_doc_chunk_tsv', table_name='doc_chunk', postgresql_using='gin')
    op.drop_table('doc_chunk')
    op.drop_table('chat_message')
    op.drop_table('user_role')
    op.drop_table('topic_term')
    op.drop_table('target')
    op.drop_table('sync_batch')
    op.drop_table('report')
    op.drop_table('recovery_plan')
    op.drop_table('document')
    op.drop_table('conflict_flag')
    op.drop_table('chat_session')
    op.drop_index('ix_audit_entity', table_name='audit_event')
    op.drop_index('ix_audit_created', table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_table('approval_task')
    op.drop_table('approval_level')
    op.drop_table('weather_observation')
    op.drop_table('weather_forecast')
    op.drop_table('topic')
    op.drop_table('bench')
    op.drop_table('approval_chain')
    op.drop_table('app_user')
    op.drop_table('role_permission')
    op.drop_table('report_template_version')
    op.drop_table('mine')
    op.drop_table('role')
    op.drop_table('report_template')
    op.drop_table('permission')
    op.drop_table('org_unit')
    op.drop_index(op.f('ix_calc_run_input_hash'), table_name='calc_run')
    op.drop_table('calc_run')
    # ### end Alembic commands ###
