"""tier4 tables: meeting_action, knowledge_entry, safety_incident, safety_pattern, photo_evidence

Revision ID: ab07b372d6a8
Revises: fe133e64440f
Create Date: 2026-10-05 18:37:04.059645
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ab07b372d6a8'
down_revision: Union[str, None] = 'fe133e64440f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_pattern',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('pattern_name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('ROOF_FALL', 'SLOPE_FAILURE', 'EQUIPMENT', 'BLASTING', 'ELECTRICAL', 'TRANSPORT', 'FIRE', 'GAS', 'WATER_INRUSH', 'OTHER', name='safety_pattern_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('GEOLOGICAL', 'OPERATIONAL', 'SAFETY', 'EQUIPMENT', 'ENVIRONMENTAL', 'REGULATORY', name='knowledge_category'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_designation', sa.String(length=255), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_action',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('meeting_type', sa.Enum('SAFETY', 'PRODUCTION', 'PLANNING', 'REVIEW', 'EMERGENCY', name='meeting_type'), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=False),
    sa.Column('assigned_role', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', name='meeting_action_status'), nullable=False),
    sa.Column('completion_notes', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('bench_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('photo_latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('photo_longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('photo_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('expected_longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'SUSPICIOUS', name='photo_verification_status'), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=False),
    sa.Column('context', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bench_id'], ['bench.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_incident',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('bench_id', sa.UUID(), nullable=True),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.Enum('ROOF_FALL', 'SLOPE_FAILURE', 'EQUIPMENT', 'BLASTING', 'ELECTRICAL', 'TRANSPORT', 'FIRE', 'GAS', 'WATER_INRUSH', 'OTHER', name='incident_category'), nullable=False),
    sa.Column('severity', sa.Enum('NEAR_MISS', 'MINOR', 'MODERATE', 'SERIOUS', 'FATAL', name='incident_severity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_description', sa.String(length=500), nullable=False),
    sa.Column('workers_involved', sa.Integer(), nullable=False),
    sa.Column('injuries', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('corrective_actions', sa.Text(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bench_id'], ['bench.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_safety_incident_mine_date', 'safety_incident', ['mine_id', 'incident_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_safety_incident_mine_date', table_name='safety_incident')
    op.drop_table('safety_incident')
    op.drop_table('photo_evidence')
    op.drop_table('meeting_action')
    op.drop_table('knowledge_entry')
    op.drop_table('safety_pattern')
    # ### end Alembic commands ###
