"""innovations_pq_quality_ledger_handover_compliance_explosives_geology

Revision ID: fe133e64440f
Revises: 4e47b85cd03f
Create Date: 2026-10-04 00:16:52.656323
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe133e64440f'
down_revision: Union[str, None] = '4e47b85cd03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_pattern',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('PRODUCTION', 'SAFETY', 'ENVIRONMENT', 'FINANCE', 'LAND_DISPLACEMENT', 'IMPORT_EXPORT', 'PROCUREMENT', 'EMPLOYEES', 'OTHER', name='pq_category'), nullable=False),
    sa.Column('trigger_type', sa.Enum('SEASONAL', 'INCIDENT', 'POLICY', 'BUDGET', name='pq_trigger_type'), nullable=False),
    sa.Column('historical_frequency_10y', sa.Integer(), nullable=False),
    sa.Column('typical_months', sa.JSON(), nullable=False, comment='Months 1-12 in which this pattern historically peaks'),
    sa.Column('trigger_conditions', sa.JSON(), nullable=False, comment='e.g. {metric: production_tonnes, drop_pct: 15} or {authority: dgms}'),
    sa.Column('sample_questions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('parliamentary_question',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('house', sa.Enum('LOK_SABHA', 'RAJYA_SABHA', name='pq_house'), nullable=False),
    sa.Column('question_number', sa.String(length=50), nullable=False),
    sa.Column('asked_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_name', sa.String(length=100), nullable=False),
    sa.Column('member_name', sa.String(length=255), nullable=False),
    sa.Column('constituency', sa.String(length=255), nullable=False),
    sa.Column('ministry', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('PRODUCTION', 'SAFETY', 'ENVIRONMENT', 'FINANCE', 'LAND_DISPLACEMENT', 'IMPORT_EXPORT', 'PROCUREMENT', 'EMPLOYEES', 'OTHER', name='pq_category'), nullable=False),
    sa.Column('pattern_id', sa.UUID(), nullable=True),
    sa.Column('days_to_answer', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['question_pattern.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_obligation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=True, comment='NULL = applies to all mines'),
    sa.Column('authority', sa.Enum('DGMS', 'MOEF', 'STATE_PCB', 'COAL_CONTROLLER', 'MINISTRY_OF_COAL', name='compliance_authority'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'ANNUAL', name='compliance_frequency'), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False, comment='Day of month the filing is due'),
    sa.Column('required_metrics', sa.JSON(), nullable=False, comment='MetricNames that must be present for the period'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_pack',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pattern_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('likelihood_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'STALE', 'SUBMITTED', name='evidence_pack_status'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False, comment='Named sections; figures carry lineage refs for Replay the Number'),
    sa.Column('data_as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['question_pattern.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('explosive_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('bench_id', sa.UUID(), nullable=True),
    sa.Column('log_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('explosives_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ob_m3', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('coal_tonnes', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('kg_per_m3', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('baseline_kg_per_m3', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('deviation_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('flag', sa.Enum('NORMAL', 'OVER_CONSUMPTION', 'UNDER_CONSUMPTION', name='explosive_flag'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bench_id'], ['bench.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geological_prediction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('bench_id', sa.UUID(), nullable=True),
    sa.Column('seam_name', sa.String(length=100), nullable=False),
    sa.Column('predicted_thickness_m', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('predicted_gcv', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tolerance_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bench_id'], ['bench.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loss_ledger_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('loss_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cause_type', sa.Enum('RAIN_WEATHER', 'EQUIPMENT_FAILURE', 'FIRE_MAJOR_INCIDENT', 'LABOUR_DISRUPTION', 'SUPPLY', 'POWER_FAILURE', 'BLASTING_DELAY', 'OTHER', name='loss_cause_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tonnes_lost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('hours_lost', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('source_type', sa.Enum('CAUSE_RECORD', 'ANOMALY', 'MANUAL', name='loss_source_type'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('recovery_status', sa.Enum('OPEN', 'PARTIAL', 'RECOVERED', 'WAIVED', name='loss_recovery_status'), nullable=False),
    sa.Column('recovered_tonnes', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_prediction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('bench_id', sa.UUID(), nullable=True),
    sa.Column('prediction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('baseline_gcv', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('predicted_gcv', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('declared_gcv', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deviation_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='quality_risk'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'LAB_CONFIRMED', 'SLIPPAGE_FLAGGED', name='quality_prediction_status'), nullable=False),
    sa.Column('basis', sa.JSON(), nullable=False, comment='Samples/months used for the baseline; evidence for Replay'),
    sa.Column('lab_gcv', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lab_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bench_id'], ['bench.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_sample',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('bench_id', sa.UUID(), nullable=True),
    sa.Column('sample_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gcv_kcal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bench_id'], ['bench.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_handover',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('shift_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outgoing_shift', sa.Enum('FIRST', 'SECOND', 'THIRD', name='handover_outgoing_shift'), nullable=False),
    sa.Column('brief', sa.JSON(), nullable=False, comment='production, pending, equipment, safety, weather, notes sections'),
    sa.Column('critical_items', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_filing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'INCOMPLETE', 'READY', 'SUBMITTED', 'LATE', name='filing_status'), nullable=False),
    sa.Column('completion_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('missing_metrics', sa.JSON(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mine.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['compliance_obligation.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geological_observation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('observed_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_thickness_m', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('actual_gcv', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('thickness_dev_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('gcv_dev_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('severity', sa.Enum('WITHIN_TOLERANCE', 'MODERATE', 'SEVERE', name='deviation_severity'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['geological_prediction.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geological_observation')
    op.drop_table('compliance_filing')
    op.drop_table('shift_handover')
    op.drop_table('quality_sample')
    op.drop_table('quality_prediction')
    op.drop_table('loss_ledger_entry')
    op.drop_table('geological_prediction')
    op.drop_table('explosive_log')
    op.drop_table('evidence_pack')
    op.drop_table('compliance_obligation')
    op.drop_table('parliamentary_question')
    op.drop_table('question_pattern')
    # ### end Alembic commands ###
